### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by domainmurat** [aspnetboilerplate/module-zero-core-template#111]
When i  build module-zero project getting error on the entityframeworkcore phase. 

Error -> 
{
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "GenerateBindingRedirects" task failed unexpectedly.
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.Build.Shared.FileUtilities.OpenWrite(String path, Boolean append, Encoding encoding)
   at Microsoft.Build.Tasks.GenerateBindingRedirects.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	AbpCompanyName.AbpProjectName.EntityFrameworkCore	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	2099	
}

**Comment by acjh** [comment]
> System.IO.PathTooLongException: The specified path, file name, or both are too long.

Where is your project located?

**Comment by domainmurat** [comment]
Into :C\

**Comment by acjh** [comment]
How long is `FolderName`? Can you try building it on `Desktop`?

**Comment by domainmurat** [comment]
I tried on Desktop. Still Not Build.

**Comment by ismcagdas** [comment]
Hi @domainmurat, sometimes extracted solution folder can be very long.
Can you move your downloaded solution to a shorter path and try again ?

If it does not work, can you share your solution's full path ?
