### ISSUE TITLE
An internal error occurred during your request!

### ISSUE THREAD

**Issue by ahmed-sherien** [aspnetboilerplate/module-zero-core-template#195]
I'm working on a list of localized data and it keeps giving me this error even though no exceptions is thrown in code.

Entities:

``` csharp
public interface IHaveTranslations<T>
        where T : TranslationEntity
    {
        ICollection<T> Translations { get; set; }
    }

public abstract class TranslationEntity : FullAuditedEntity, IMustHaveTenant
    {
        public virtual ApplicationLanguage Language { get; set; }
        public virtual int LanguageId { get; set; }
        public virtual int TenantId { get; set; }
    }

public class UnitOfMeasure : FullAuditedEntity, IMustHaveTenant, IHaveTranslations<UnitOfMeasureTranslation>
    {
        public virtual int TenantId { get; set; }
        public virtual ICollection<UnitOfMeasureTranslation> Translations { get; set; }
    }

public class UnitOfMeasureTranslation : TranslationEntity
    {
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual int UnitOfMeasureId { get; set; }

        public virtual string Name { get; set; }
    }
```

Dto:

``` csharp
public class UnitOfMeasureListItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
```

Mapper:

``` csharp
configuration.CreateMap<UnitOfMeasure, UnitOfMeasureListItem>()
                .ForMember(dto => dto.Name, options => MapFromTranslated<UnitOfMeasure, UnitOfMeasureTranslation, UnitOfMeasureListItem>(options, t => t.Name));

private static void MapFromTranslated<TSource, TTranslation, TDestination>(IMemberConfigurationExpression<TSource, TDestination, string> options, Expression<Func<TTranslation, string>> member)
            where TSource : IHaveTranslations<TTranslation>
            where TTranslation : TranslationEntity
        {
            options.MapFrom(uom => MapTranslation(uom, member));
            options.MapAtRuntime();
        }

private static TMember MapTranslation<TSource, TTranslation, TMember>(TSource entity, Expression<Func<TTranslation, TMember>> member)
            where TSource : IHaveTranslations<TTranslation>
            where TTranslation : TranslationEntity
        {
            var languageName = CultureInfo.CurrentUICulture.Name.Split('-').FirstOrDefault();
            var translation = entity.Translations.FirstOrDefault(t => t.Language.Name.Contains(languageName)) ?? entity.Translations.FirstOrDefault(t => t.LanguageId == 1);
            var translationParameter = Expression.Parameter(typeof(TTranslation), "t");
            var targetProperty = Expression.Property(translationParameter, ((MemberExpression)member.Body).Member.Name);
            var action = Expression.Lambda<Func<TTranslation, TMember>>(targetProperty, translationParameter);
            return action.Compile().Invoke(translation);
        }
```

App Service:

``` csharp
private readonly IApplicationLanguageManager _applicationLanguageManager;
        private readonly IRepository<UnitOfMeasure> _unitsOfMeasureRepository;
        private readonly IRepository<UnitOfMeasureTranslation> _unitOfMeasureTranslationsRepository;

        private readonly List<ApplicationLanguage> _languages;
        public UnitsOfMeasureAppService(IApplicationLanguageManager applicationLanguageManager,
                                        IRepository<UnitOfMeasure> unitsOfMeasureRepository,
                                        IRepository<UnitOfMeasureTranslation> unitOfMeasureTranslationsRepository)
        {
            _applicationLanguageManager = applicationLanguageManager;
            _unitsOfMeasureRepository = unitsOfMeasureRepository;
            _unitOfMeasureTranslationsRepository = unitOfMeasureTranslationsRepository;

            _languages = _applicationLanguageManager.GetLanguagesAsync(AbpSession.TenantId).GetAwaiter().GetResult().ToList();
        }

public ListResultDto<UnitOfMeasureListItem> GetUnitsOfMeasure()
        {
            var unitsOfMeasure = _unitsOfMeasureRepository.GetAllIncluding(u => u.Translations).ToList();
            unitsOfMeasure.ForEach(u =>
            {
                u.Translations.ToList().ForEach(t => t.Language = _languages.FirstOrDefault(l => l.Id == t.LanguageId));
            });

            var mapped = new ListResultDto<UnitOfMeasureListItem>(ObjectMapper.Map<List<UnitOfMeasureListItem>>(unitsOfMeasure));
            return mapped;
        }
```

Logs:

```
INFO  2018-03-01 17:04:30,388 [16   ] soft.AspNetCore.Hosting.Internal.WebHost - Request starting HTTP/1.1 GET http://localhost:22742/api/services/app/UnitsOfMeasure/GetUnitsOfMeasure  
INFO  2018-03-01 17:04:30,623 [16   ] ore.Mvc.Internal.ControllerActionInvoker - Executing action method pos.POS.BackOffice.UnitsOfMeasure.UnitsOfMeasureAppService.GetUnitsOfMeasure (pos.Application) with arguments ((null)) - ModelState is Valid
ERROR 2018-03-01 17:04:30,944 [16   ] Mvc.ExceptionHandling.AbpExceptionFilter - An error occurred while updating the entries. See the inner exception for details.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Cannot insert explicit value for identity column in table 'AbpLanguages' when IDENTITY_INSERT is set to OFF.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__108_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Abp.EntityFrameworkCore.AbpDbContext.<SaveChangesAsync>d__49.MoveNext() in D:\Github\aspnetboilerplate\src\Abp.EntityFrameworkCore\EntityFrameworkCore\AbpDbContext.cs:line 215
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Abp.EntityFrameworkCore.Uow.EfCoreUnitOfWork.<SaveChangesInDbContextAsync>d__20.MoveNext() in D:\Github\aspnetboilerplate\src\Abp.EntityFrameworkCore\EntityFrameworkCore\Uow\EfCoreUnitOfWork.cs:line 163
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Abp.EntityFrameworkCore.Uow.EfCoreUnitOfWork.<SaveChangesAsync>d__12.MoveNext() in D:\Github\aspnetboilerplate\src\Abp.EntityFrameworkCore\EntityFrameworkCore\Uow\EfCoreUnitOfWork.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Abp.EntityFrameworkCore.Uow.EfCoreUnitOfWork.<CompleteUowAsync>d__14.MoveNext() in D:\Github\aspnetboilerplate\src\Abp.EntityFrameworkCore\EntityFrameworkCore\Uow\EfCoreUnitOfWork.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Abp.Domain.Uow.UnitOfWorkBase.<CompleteAsync>d__57.MoveNext() in D:\Github\aspnetboilerplate\src\Abp\Domain\Uow\UnitOfWorkBase.cs:line 276
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Abp.AspNetCore.Mvc.Uow.AbpUowActionFilter.<OnActionExecutionAsync>d__4.MoveNext() in D:\Github\aspnetboilerplate\src\Abp.AspNetCore\AspNetCore\Mvc\Uow\AbpUowActionFilter.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()
INFO  2018-03-01 17:04:31,116 [16   ] etCore.Mvc.Internal.ObjectResultExecutor - Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
INFO  2018-03-01 17:04:31,131 [16   ] ore.Mvc.Internal.ControllerActionInvoker - Executed action pos.POS.BackOffice.UnitsOfMeasure.UnitsOfMeasureAppService.GetUnitsOfMeasure (pos.Application) in 724.1015ms
INFO  2018-03-01 17:04:31,132 [16   ] soft.AspNetCore.Hosting.Internal.WebHost - Request finished in 743.436ms 500 application/json; charset=utf-8
```
App Service Response:

``` json
{
  "result": null,
  "targetUrl": null,
  "success": false,
  "error": {
    "code": 0,
    "message": "An internal error occurred during your request!",
    "details": null,
    "validationErrors": null
  },
  "unAuthorizedRequest": false,
  "__abp": true
}
```

Any help will be greatly appreciated ...

**Comment by acjh** [comment]
EF Core automatically [adds a related entity](https://docs.microsoft.com/en-us/ef/core/saving/related-data#adding-a-related-entity):

> If you reference a new entity from the navigation property of an entity that is already tracked by the context, the entity will be discovered and inserted into the database.

Solution:

```c#
public ListResultDto<UnitOfMeasureListItem> GetUnitsOfMeasure()
{
    var unitsOfMeasure = _unitsOfMeasureRepository.GetAllIncluding(u => u.Translations)
                                                  .AsNoTracking() // This
                                                  .ToList();
    // ...
}
```

**Comment by ahmed-sherien** [comment]
Thanks that did it ...
