### ISSUE TITLE
Javascript errors with running in dev (localhost)

### ISSUE THREAD

**Issue by Cephei** [aspnetboilerplate/module-zero-core-template#72]
I'm getting runtime errors:

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'input' of undefined
TypeError: Cannot read property 'input' of undefined
    at LoginComponent.webpackJsonp.../../../../../src/account/login/login.component.ts.LoginComponent.ngAfterViewInit
```

**Comment by hikalkan** [comment]
have you installed nmp packages?

**Comment by AlanFlaherty** [comment]
Is the "../src/bsb-theme/js/admin.js" script missing somehow?

**Comment by Cephei** [comment]
I'll take a look as soon as I get home. Thanks for the quick feedback! @hikalkan, I have run `npm install`

**Comment by Cephei** [comment]
@AlanFlaherty I do have that file. I just generated a new ABP solution using the online tool. Still no luck with this issue though.

**Comment by Cephei** [comment]
```
core.es5.js:1084 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'input' of undefined
TypeError: Cannot read property 'input' of undefined
    at LoginComponent.webpackJsonp.../../../../../src/account/login/login.component.ts.LoginComponent.ngAfterViewInit (http://localhost:4200/1.chunk.js:375:19)
    at callProviderLifecycles (http://localhost:4200/vendor.bundle.js:100927:18)
    at callElementProvidersLifecycles (http://localhost:4200/vendor.bundle.js:100902:13)
    at callLifecycleHooksChildrenFirst (http://localhost:4200/vendor.bundle.js:100886:17)
    at checkAndUpdateView (http://localhost:4200/vendor.bundle.js:101908:5)
    at callWithDebugContext (http://localhost:4200/vendor.bundle.js:102888:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (http://localhost:4200/vendor.bundle.js:102428:12)
    at ViewRef_.webpackJsonp.../../../core/@angular/core.es5.js.ViewRef_.detectChanges (http://localhost:4200/vendor.bundle.js:99997:63)
    at RouterOutlet.webpackJsonp.../../../router/@angular/router.es5.js.RouterOutlet.activateWith (http://localhost:4200/vendor.bundle.js:122750:42)
    at ActivateRoutes.webpackJsonp.../../../router/@angular/router.es5.js.ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:121931:16)
    at ActivateRoutes.webpackJsonp.../../../router/@angular/router.es5.js.ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:121912:26)
    at http://localhost:4200/vendor.bundle.js:121848:58
    at Array.forEach (native)
    at ActivateRoutes.webpackJsonp.../../../router/@angular/router.es5.js.ActivateRoutes.activateChildRoutes (http://localhost:4200/vendor.bundle.js:121848:29)
    at ActivateRoutes.webpackJsonp.../../../router/@angular/router.es5.js.ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:121913:26)
    at LoginComponent.webpackJsonp.../../../../../src/account/login/login.component.ts.LoginComponent.ngAfterViewInit (http://localhost:4200/1.chunk.js:375:19)
    at callProviderLifecycles (http://localhost:4200/vendor.bundle.js:100927:18)
    at callElementProvidersLifecycles (http://localhost:4200/vendor.bundle.js:100902:13)
    at callLifecycleHooksChildrenFirst (http://localhost:4200/vendor.bundle.js:100886:17)
    at checkAndUpdateView (http://localhost:4200/vendor.bundle.js:101908:5)
    at callWithDebugContext (http://localhost:4200/vendor.bundle.js:102888:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (http://localhost:4200/vendor.bundle.js:102428:12)
    at ViewRef_.webpackJsonp.../../../core/@angular/core.es5.js.ViewRef_.detectChanges (http://localhost:4200/vendor.bundle.js:99997:63)
    at RouterOutlet.webpackJsonp.../../../router/@angular/router.es5.js.RouterOutlet.activateWith (http://localhost:4200/vendor.bundle.js:122750:42)
    at ActivateRoutes.webpackJsonp.../../../router/@angular/router.es5.js.ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:121931:16)
    at ActivateRoutes.webpackJsonp.../../../router/@angular/router.es5.js.ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:121912:26)
    at http://localhost:4200/vendor.bundle.js:121848:58
    at Array.forEach (native)
    at ActivateRoutes.webpackJsonp.../../../router/@angular/router.es5.js.ActivateRoutes.activateChildRoutes (http://localhost:4200/vendor.bundle.js:121848:29)
    at ActivateRoutes.webpackJsonp.../../../router/@angular/router.es5.js.ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:121913:26)
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:3310:31) [angular]
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:3281:17) [angular]
    at http://localhost:4200/polyfills.bundle.js:3358:17 [angular]
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:93998:37) [angular]
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:3191:35) [<root>]
    at <anonymous> [<root>]
```

**Comment by Cephei** [comment]
<img width="951" alt="screen shot 2017-06-21 at 2 03 04 pm" src="https://user-images.githubusercontent.com/1054639/27399338-6653ee2e-568a-11e7-8768-1cf74159d0c6.png">

No css appears to be rendering properly either. I've run npm install, yarn, ng build, ng serve

**Comment by Cephei** [comment]
It's not a bug in login.component.ts.LoginComponent.ngAfterViewInit. My guess is that I'm having an issue with some part of the compilation process. All my api endpoints work. All the scripts (polyfills.bundle.js, styles, main, vendor) get rendered.

**Comment by AlanFlaherty** [comment]
That is what is thought might be happening something like that the admin.js was missing from the .angular-cli.json. With missing style sheets and missing javascript files it would be the most likely. That somehow it got regenerated.

I don't use yarn

So i'd normally just:
npm install
ng serve [or "ng serve --hmr --e=hmr"]

Just having a look with a fresh project just downloaded off the website. I'll try setup yarn too just to double check.

Just to ensure please verify that you can see the deceleration for the $.AdminBSB.input in the produced scripts.bundle.js just over 3/4 of the way through the file.

**Comment by AlanFlaherty** [comment]
The version on the website does seem to work, try deleting the angular folder and replacing it with the one from the zip file you got from the website. 

Then just run these from inside the angular folder:

```
npm install 
ng serve
```

But first, please verify that the .angular-cli.json is correct.

**Comment by Cephei** [comment]
I think it's completely my fault and have probably tainted my solution. I upgraded from angular-cli to angular/cli and there's a number of things to do in this migration. I'm trying to follow along on the ngcli github wiki, but it's not working yet.

**Comment by Cephei** [comment]
https://github.com/angular/angular-cli/wiki/stories-1.0-update

**Comment by Cephei** [comment]
Got it working with just replacing the entire /angular directory with a fresh one. I'm far too inexperienced with angular cli to be trying to migrate to the latest at the moment.
