### ISSUE TITLE
Migrator.MultiTenantMigrateExecuter is waiting for the following dependencies

### ISSUE THREAD

**Issue by karakule006** [aspnetboilerplate/module-zero-core-template#98]
May Project name is OBYS.  When I execute OBYS.Migrator.exe I take this exception;

**Castle.MicroKernel.Handlers.HandlerException occurred
  HResult=0x80131500
  Message=Can't create component 'OBYS.Migrator.MultiTenantMigrateExecuter' as it has dependencies to be satisfied.

'OBYS.Migrator.MultiTenantMigrateExecuter' is waiting for the following dependencies:
- Service 'Abp.Zero.EntityFrameworkCore.AbpZeroDbMigrator`1[[OBYS.EntityFrameworkCore.OBYSDbContext, OBYS.EntityFrameworkCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' which was not registered.

  Source=Castle.Windsor
  StackTrace:
   at Castle.MicroKernel.Handlers.DefaultHandler.AssertNotWaitingForDependency()
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, IDictionary additionalArguments, IReleasePolicy policy)
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, IDictionary arguments, IReleasePolicy policy)
   at Castle.Windsor.WindsorContainer.Resolve[T]()
   at Abp.Dependency.IocResolverExtensions.ResolveAsDisposable[T](IIocResolver iocResolver)
   at OBYS.Migrator.Program.Main(String[] args) in C:\Users\deniz\Downloads\OBYS\aspnet-core\src\OBYS.Migrator\Program.cs:line 27**

I'm using free template.

**Comment by hikalkan** [comment]
Template: asp.net core & module-zero. I suppose angular/jquery selection does not effect the problem.

**Comment by alirizaadiyahsi** [comment]
We fixed it. 

You can check this: https://github.com/aspnetboilerplate/module-zero-core-template/commit/600b8687d482f537d86ba58e2ef758016c13e6f2

We will fix at website soon.
